"""initial

Revision ID: 804fb440d9f4
Revises: c4d85d1e5c81
Create Date: 2023-11-20 10:49:36.147615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804fb440d9f4'
down_revision: Union[str, None] = 'c4d85d1e5c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('stories_creator_id_fkey', 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('stories', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key('stories_creator_id_fkey', 'stories', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('stories', 'author_id')
    # ### end Alembic commands ###
