"""initial

Revision ID: 88781bd87acd
Revises: 13a0ced9e0ed
Create Date: 2023-11-24 12:42:39.650186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88781bd87acd'
down_revision: Union[str, None] = '13a0ced9e0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'picture_url')
    # ### end Alembic commands ###
