"""on update cascade for cat name

Revision ID: cda9540ee4d7
Revises: f20c170a1dee
Create Date: 2023-09-01 16:36:06.141687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda9540ee4d7'
down_revision: Union[str, None] = 'f20c170a1dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stories_category_name_fkey', 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'story_categories', ['category_name'], ['name'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key('stories_category_name_fkey', 'stories', 'story_categories', ['category_name'], ['name'])
    # ### end Alembic commands ###
