"""cascade

Revision ID: fee243eb2628
Revises: dafc8749f96d
Create Date: 2023-09-01 13:26:42.461699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee243eb2628'
down_revision: Union[str, None] = 'dafc8749f96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stories_creator_id_fkey', 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('story_comments_user_id_fkey', 'story_comments', type_='foreignkey')
    op.drop_constraint('story_comments_story_id_fkey', 'story_comments', type_='foreignkey')
    op.create_foreign_key(None, 'story_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'story_comments', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('story_rating_votes_user_id_fkey', 'story_rating_votes', type_='foreignkey')
    op.drop_constraint('story_rating_votes_story_id_fkey', 'story_rating_votes', type_='foreignkey')
    op.create_foreign_key(None, 'story_rating_votes', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'story_rating_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_rating_votes', type_='foreignkey')
    op.drop_constraint(None, 'story_rating_votes', type_='foreignkey')
    op.create_foreign_key('story_rating_votes_story_id_fkey', 'story_rating_votes', 'stories', ['story_id'], ['id'])
    op.create_foreign_key('story_rating_votes_user_id_fkey', 'story_rating_votes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'story_comments', type_='foreignkey')
    op.drop_constraint(None, 'story_comments', type_='foreignkey')
    op.create_foreign_key('story_comments_story_id_fkey', 'story_comments', 'stories', ['story_id'], ['id'])
    op.create_foreign_key('story_comments_user_id_fkey', 'story_comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key('stories_creator_id_fkey', 'stories', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
